Add a simple commands http server
fly-apps/postgres-ha pull request #64
Opened 2022-03-24 22:08 UTC by rugwirobaker

2022-03-24 23:33 UTC, davissp14 commented on pkg/commands/handler.go
> +	http.HandleFunc("/commands/users/grant", handleGrantAccess)
You can ditch the grant/revoke handlers, these operations should be handled by user create/delete.

2022-03-25 15:43 UTC, rugwirobaker commented on pkg/flycheck/checks.go
> +
@davissp14 I've put them on the same port but they are still in different packages that are imported by a new package `pkg/server`. I could rename it though.

2022-04-05 14:31 UTC, davissp14 requested changes
Found a little bug with the attach process.

2022-04-05 14:31 UTC, davissp14 commented on pkg/commands/handler.go
> +	db, err := admin.FindDatabase(r.Context(), pg, name)
This seems to return status code 500 when the the target database doesn't exist.

Flyctl expects 404: https://github.com/superfly/flyctl/blob/be327db0075b8e4bb35eda4c8359da0936b0c42d/pkg/flypg/pg.go#L92

2022-04-05 20:14 UTC, davissp14 approved these changes
Nice work!

2022-04-06 17:52 UTC, merged