Add docs for enabling TimescaleDB extension
fly-apps/postgres-ha pull request #91
Opened 2022-11-04 23:32 UTC by alukach

This surfaces the guide for enabling the TimescaleDB extension, as [written by @davissp14](https://github.com/fly-apps/postgres-ha/pull/75#issuecomment-1262416538) in #75

2022-11-05 00:23 UTC, dangra requested changes
Nice! thanks for taking the time for this.

The only difference since Shaun post is that `fly image update` is the only way to update the image for Nomad and Machines. `fly postgres update` was removed in favour for the former.

2022-11-08 18:37 UTC, alukach commented
@dangra ✅ [47272e1](https://github.com/fly-apps/postgres-ha/pull/91/commits/47272e11fe8c6e38ac80fa059bf08cf0f21895eb)

2022-11-09 01:59 UTC, dangra approved these changes

2022-11-09 02:00 UTC, merged

2022-11-09 02:00 UTC, dangra commented
Thanks!